const $ = id => document.getElementById(id);
const esc = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={sports:'Thể thao',news:'Thời sự',finance:'Tài chính',health:'Sức khỏe',travel:'Du lịch',lifestyle:'Đời sống',foodanddrink:'Ẩm thực',autos:'Xe',video:'Video',music:'Âm nhạc',tv:'Truyền hình',movies:'Điện ảnh',weather:'Thời tiết',kids:'Thiếu nhi',entertainment:'Giải trí'};
let meta, current, ranked=null, mode='impression', category='', userOffset=0, newsOffset=0, usersTotal=0, newsTotal=0, userQuery='', newsQuery='', catalog=[], busy=false;
let userRequest=0, impressionRequest=0, catalogRequest=0;
function message(text='',error=false){$('message').textContent=text;$('message').classList.toggle('error',error);}
async function api(path,options={}){const response=await fetch(path,{...options,signal:AbortSignal.timeout(60000)});if(!response.ok)throw Error(`API lỗi ${response.status}. Kiểm tra dữ liệu và vector MIND trong Docker.`);return response.json();}
function fail(error){message(error.name==='TimeoutError'?'Tải dữ liệu quá thời gian chờ. Hãy tải lại trang.':error.message,true);}
function filters(){const cats=mode==='catalog'?(meta?.categories||[]):[...new Set((current?.candidates||[]).map(n=>n.category))];$('filters').innerHTML=[['','Tất cả'],...cats.map(c=>[c,names[c]||c])].map(([c,label])=>`<button data-category="${esc(c)}" class="${category===c?'active':''}" aria-pressed="${category===c}">${esc(label)}</button>`).join('');}
function render(){
 const all=mode==='catalog'?catalog:(ranked||current?.candidates||[]);const shown=mode==='catalog'?all:all.filter(n=>!category||n.category===category);
 $('feed-title').textContent=mode==='catalog'?'Kho tin MIND':ranked?'Dành riêng cho '+current.user_id:'Tin được hiển thị';
 $('news-count').textContent=`${mode==='catalog'?newsTotal:all.length} tin`;
 $('results-meta').textContent=mode==='catalog'?'TIN GỐC TỪ NEWS.TSV':ranked?'XẾP THEO ĐIỂM · 75% NGỮ NGHĨA + 25% CHỦ ĐỀ':'THỨ TỰ GỐC TRONG LƯỢT HIỂN THỊ MIND';
 $('empty').hidden=shown.length>0;
 $('news-grid').innerHTML=shown.map(n=>{const scored=mode==='impression'&&ranked;return `<article class="card"><div class="art ${n.category==='sports'?'sport':n.category==='finance'?'business':'world'}">${scored?`<span class="rank">GỢI Ý #${all.indexOf(n)+1}</span>`:''}<span class="art-word">${esc(n.category.toUpperCase())}</span></div><div class="card-content"><div class="category">${esc(n.news_id)} · ${esc(names[n.category]||n.category)}</div><h3>${esc(n.title)}</h3><p class="abstract">${esc(n.abstract||'Không có tóm tắt trong dữ liệu MIND.')}</p>${scored?`<div class="scores"><div class="score-main"><span>Điểm phù hợp</span><strong>${n.score.toFixed(4)}</strong></div><div class="bar"><span style="width:${Math.max(0,Math.min(100,n.score*100))}%"></span></div><div class="score-detail">Ngữ nghĩa ${n.semantic_score.toFixed(4)} · Chủ đề ${n.topic_score.toFixed(4)}</div></div>`:''}<div class="card-bottom"><span>${esc(n.subcategory)}</span>${mode==='impression'?`<span class="${n.clicked?'clicked':'not-clicked'}">${n.clicked?'✓ Đã click trong MIND':'Không click trong MIND'}</span>`:'<span>MIND archive</span>'}</div></div></article>`;}).join('');
 $('catalog-search').hidden=mode!=='catalog';$('catalog-pager').hidden=mode!=='catalog';
 $('prev-news').disabled=busy||newsOffset===0;$('next-news').disabled=busy||newsOffset+20>=newsTotal;
 $('news-page').textContent=newsTotal?`${newsOffset+1}–${Math.min(newsOffset+20,newsTotal)} / ${newsTotal}`:'0 tin';
}
async function loadImpression(id){const ticket=++impressionRequest;current=null;ranked=null;$('recommend').disabled=true;$('history-options').replaceChildren();$('history-count').textContent='0 tin';$('profile-info').textContent='';render();if(!id)return;message('Đang tải lịch sử và tin ứng viên…');try{const data=await api('/mind/impressions/'+encodeURIComponent(id));if(ticket!==impressionRequest)return;current=data;category='';$('profile-info').textContent=`${data.user_id} · Lượt ${id} · ${data.timestamp}`;$('history-count').textContent=`${data.history.length} tin`;$('history-options').innerHTML=data.history.map(n=>`<div class="history-item"><small>${esc(n.news_id)} · ${esc(names[n.category]||n.category)}</small>${esc(n.title)}</div>`).join('');$('recommend').disabled=false;filters();render();message();}catch(e){if(ticket===impressionRequest)fail(e);}}
async function loadUsers(){const ticket=++userRequest;$('impression-select').disabled=true;$('recommend').disabled=true;try{const data=await api(`/mind/impressions?offset=${userOffset}&limit=20&user=${encodeURIComponent(userQuery)}`);if(ticket!==userRequest)return;usersTotal=data.total;$('impression-select').innerHTML=data.items.map(n=>`<option value="${esc(n.impression_id)}">${esc(n.user_id)} · Lượt ${esc(n.impression_id)} · ${n.candidate_count} tin</option>`).join('');$('impression-select').disabled=!data.items.length;$('prev-users').disabled=userOffset===0;$('next-users').disabled=userOffset+20>=usersTotal;$('user-page').textContent=usersTotal?`${userOffset+1}–${Math.min(userOffset+20,usersTotal)} / ${usersTotal}`:'0 lượt';await loadImpression(data.items[0]?.impression_id);if(!data.items.length)message('Không tìm thấy người dùng có lượt đọc đủ dữ liệu.');}catch(e){if(ticket===userRequest)fail(e);}}
async function loadCatalog(){const ticket=++catalogRequest;catalog=[];render();message('Đang tải kho tin…');try{const data=await api(`/mind/news?offset=${newsOffset}&limit=20&q=${encodeURIComponent(newsQuery)}&category=${encodeURIComponent(category)}`);if(ticket!==catalogRequest||mode!=='catalog')return;catalog=data.items;newsTotal=data.total;render();message();}catch(e){if(ticket===catalogRequest)fail(e);}}
$('impression-select').addEventListener('change',e=>loadImpression(e.target.value));
$('user-form').addEventListener('submit',e=>{e.preventDefault();userQuery=$('user-query').value.trim();userOffset=0;loadUsers();});
$('prev-users').onclick=()=>{userOffset=Math.max(0,userOffset-20);loadUsers();};$('next-users').onclick=()=>{userOffset+=20;loadUsers();};
$('filters').onclick=e=>{const b=e.target.closest('[data-category]');if(!b)return;category=b.dataset.category;filters();if(mode==='catalog'){newsOffset=0;loadCatalog();}else render();};
for(const target of ['impression','catalog'])$('mode-'+target).onclick=()=>{mode=target;category='';catalogRequest++;for(const m of ['impression','catalog']){$('mode-'+m).classList.toggle('active',m===mode);$('mode-'+m).setAttribute('aria-pressed',String(m===mode));}filters();message();render();if(mode==='catalog')loadCatalog();};
$('catalog-search').onsubmit=e=>{e.preventDefault();newsQuery=$('news-query').value.trim();newsOffset=0;loadCatalog();};
$('prev-news').onclick=()=>{newsOffset=Math.max(0,newsOffset-20);loadCatalog();};$('next-news').onclick=()=>{newsOffset+=20;loadCatalog();};
$('recommend').onclick=async()=>{if(!current||busy)return;const id=current.impression_id;busy=true;$('recommend').disabled=true;$('recommend').textContent='Đang xếp hạng…';message('Đang tính điểm từ vector MIND đã lưu…');try{const data=await api('/mind/impressions/'+encodeURIComponent(id)+'/recommend',{method:'POST'});if(current?.impression_id!==id)return;ranked=data.results;$('mode-impression').click();message('Đã xếp hạng từ vector của lần chạy MIND. Nhãn click không tham gia tính điểm. Điểm tương đồng không phải xác suất.');}catch(e){fail(e);}finally{busy=false;$('recommend').disabled=!current;$('recommend').innerHTML='Xếp hạng tin cho người này <span>↗</span>';render();}};
(async()=>{try{meta=await api('/mind/metadata');$('health').textContent='● MIND đã sẵn sàng';$('dataset-info').innerHTML=`<strong>${esc(meta.dataset)} / ${esc(meta.split.toUpperCase())}</strong> · ${meta.news_count.toLocaleString('vi')} tin · ${meta.impression_count.toLocaleString('vi')} lượt có đủ dữ liệu<small>${esc(meta.sentence_model)} · ${meta.topic_dimensions} chiều chủ đề · Dùng vector đã lưu từ lần chạy MIND. ${meta.skipped_impressions.toLocaleString('vi')} lượt thiếu lịch sử hoặc thiếu tin không được đưa vào demo.</small><small>Đây là demo trên tập ${esc(meta.split)}, không phải kết quả đánh giá trên tập dev. Nội dung và nhãn click giữ nguyên từ MIND.</small>`;filters();await loadUsers();}catch(e){$('health').textContent='○ Chưa tải được MIND';fail(e);}})();
